site_name: IMGW Climate date crawler
repo_url: https://github.com/michalq/imgw-reader
repo_name: IMGW Reader
theme:
  features:
    - navigation.instant
    - navigation.footer
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.top
  language: en
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
nav:
  - Stations:
      - List: stations/list.md
  - Measurements:
      - Skierniewice: measurements/skierniewice.md
plugins:
  - search
  - awesome-pages
  - swagger-ui-tag
  - minify:
      cache_safe: true
      htmlmin_opts:
        remove_comments: true
      minify_css: true
      minify_html: true
      minify_js: true
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - class: mermaid
          format: ""
          name: mermaid
extra:
  consent:
    description: We use cookies to recognize your repeated visits and preferences, as well as to measure the effectiveness of our documentation and whether users find what they're searching for. With your consent, you're helping us to make our documentation better.
    title: Cookie consent
